name: ci
on:
  push:
    branches:
      - 'main'
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: install
        run: npm ci

      - name: test
        run: npm test

      - name: lint
        run: npm run lint
